local Gem = require("src.entities.gem")
local GameObject = require("src.entities.GameObject")

describe("Gem", function()
    it("should extend from GameObject", function()
        local gem = Gem.new()
        assert.is_true(getmetatable(gem).__index == Gem)
        assert.is_true(getmetatable(Gem).__index == GameObject)
    end)

    it("should initialize with default properties", function()
        local gem = Gem.new()
        assert.are.equal(0, gem.x)
        assert.are.equal(0, gem.y)
        assert.are.equal(0, gem.width)
        assert.are.equal(0, gem.height)
        assert.is_nil(gem.color)
        assert.is_nil(gem.type)
        assert.are.equal("idle", gem:getState())
    end)

    it("should set and get position", function()
        local gem = Gem.new()
        gem:setPosition(10, 20)
        local x, y = gem:getPosition()
        assert.are.equal(10, x)
        assert.are.equal(20, y)
    end)

    it("should set and get dimensions", function()
        local gem = Gem.new()
        gem:setDimensions(30, 40)
        assert.are.equal(30, gem.width)
        assert.are.equal(40, gem.height)
    end)

    it("should set and get color", function()
        local gem = Gem.new()
        gem:setColor("red")
        assert.are.equal("red", gem:getColor())
    end)

    it("should set and get type", function()
        local gem = Gem.new()
        gem:setType("regular")
        assert.are.equal("regular", gem:getType())
    end)
end) 